.TH "eth_header" 3 "Fri May 13 2016" "Version 1.0" "packet-generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
eth_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethheader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBeth_header\fP ()"
.br
.ti -1c
.RI "\fBeth_header\fP (std::string _dest, std::string _src)"
.br
.ti -1c
.RI "virtual \fB~eth_header\fP ()"
.br
.ti -1c
.RI "void \fBupdateSrcMAC\fP (\fBeth_header\fP *obj, std::string _src)"
.br
.ti -1c
.RI "void \fBupdateDestMAC\fP (\fBeth_header\fP *obj, std::string _dest)"
.br
.ti -1c
.RI "void \fBserializeEth\fP (\fBeth_header\fP *obj, u_char *_buff)"
.br
.ti -1c
.RI "void \fBrandomMACAddr\fP (u_char *&buffer, bool _rand_dest_flag, bool _rand_src_flag)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "u_char \fBDestMac\fP [6]"
.br
.ti -1c
.RI "u_char \fBSrcMac\fP [6]"
.br
.ti -1c
.RI "u_char \fBType\fP [2]"
.br
.ti -1c
.RI "u_char * \fBbuff\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file ethheader\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "eth_header::eth_header ()"

.PP
Definition at line 10 of file ethheader\&.cpp\&.
.SS "eth_header::eth_header (std::string_dest, std::string_src)"

.PP
Definition at line 25 of file ethheader\&.cpp\&.
.SS "eth_header::~eth_header ()\fC [virtual]\fP"

.PP
Definition at line 54 of file ethheader\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void eth_header::randomMACAddr (u_char *&buffer, bool_rand_dest_flag, bool_rand_src_flag)"

.PP
Definition at line 108 of file ethheader\&.cpp\&.
.SS "void eth_header::serializeEth (\fBeth_header\fP *obj, u_char *_buff)"

.PP
Definition at line 88 of file ethheader\&.cpp\&.
.SS "void eth_header::updateDestMAC (\fBeth_header\fP *obj, std::string_dest)"

.PP
Definition at line 75 of file ethheader\&.cpp\&.
.SS "void eth_header::updateSrcMAC (\fBeth_header\fP *obj, std::string_src)"

.PP
Definition at line 62 of file ethheader\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "u_char* eth_header::buff = NULL\fC [private]\fP"

.PP
Definition at line 35 of file ethheader\&.h\&.
.SS "u_char eth_header::DestMac[6]\fC [private]\fP"

.PP
Definition at line 30 of file ethheader\&.h\&.
.SS "u_char eth_header::SrcMac[6]\fC [private]\fP"

.PP
Definition at line 31 of file ethheader\&.h\&.
.SS "u_char eth_header::Type[2]\fC [private]\fP"

.PP
Definition at line 32 of file ethheader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for packet-generator from the source code\&.
