.TH "ip_header" 3 "Fri May 13 2016" "Version 1.0" "packet-generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ip_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipheader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBip_header\fP ()"
.br
.ti -1c
.RI "\fBip_header\fP (std::string _dest, std::string _src)"
.br
.ti -1c
.RI "virtual \fB~ip_header\fP ()"
.br
.ti -1c
.RI "void \fBupdateSrcIP\fP (\fBip_header\fP *obj, std::string _src)"
.br
.ti -1c
.RI "void \fBupdateDestIP\fP (\fBip_header\fP *obj, std::string _dest)"
.br
.ti -1c
.RI "void \fBupdateValues\fP (\fBip_header\fP *obj, u_char _ToS, unsigned short int _length, unsigned short int _id, unsigned short int _flags, unsigned short int _offset, u_char _ttl, u_char _protocol)"
.br
.ti -1c
.RI "void \fBserializeIP\fP (\fBip_header\fP *obj, u_char *\fBbuff\fP)"
.br
.ti -1c
.RI "short unsigned int \fBcalculateChecksum\fP (\fBip_header\fP *obj, u_char *\fBbuff\fP, int n)"
.br
.ti -1c
.RI "void \fBrandID\fP (\fBip_header\fP *obj, u_char *&buffer, bool _vlan)"
.br
.ti -1c
.RI "void \fBrandTTL\fP (\fBip_header\fP *obj, u_char *&buffer, bool _vlan)"
.br
.ti -1c
.RI "void \fBrandIP\fP (\fBip_header\fP *obj, u_char *&buffer, bool _vlan, bool _src_ip_flag, bool _dest_ip_flag)"
.br
.ti -1c
.RI "void \fBupdateLength\fP (unsigned short int _length)"
.br
.ti -1c
.RI "unsigned int \fBgetSrcIP\fP ()"
.br
.ti -1c
.RI "unsigned int \fBgetDestIP\fP ()"
.br
.ti -1c
.RI "u_char \fBgetProtocol\fP ()"
.br
.ti -1c
.RI "void \fBsetProtocol\fP (u_char _protocol)"
.br
.ti -1c
.RI "unsigned short int \fBgetLength\fP ()"
.br
.ti -1c
.RI "void \fBsetLength\fP (unsigned short int _length)"
.br
.ti -1c
.RI "void \fBupdateProtocol\fP (\fBip_header\fP *obj, u_char _protocol)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "u_char \fBver\fP"
.br
.ti -1c
.RI "u_char \fBihl\fP"
.br
.ti -1c
.RI "u_char \fBToS\fP"
.br
.ti -1c
.RI "unsigned short int \fBlength\fP"
.br
.ti -1c
.RI "unsigned short int \fBid\fP"
.br
.ti -1c
.RI "unsigned short int \fBflags\fP"
.br
.ti -1c
.RI "unsigned short int \fBoffset\fP"
.br
.ti -1c
.RI "u_char \fBttl\fP"
.br
.ti -1c
.RI "u_char \fBprotocol\fP"
.br
.ti -1c
.RI "short unsigned int \fBchecksum\fP"
.br
.ti -1c
.RI "unsigned int \fBsourceip\fP"
.br
.ti -1c
.RI "unsigned int \fBdestip\fP"
.br
.ti -1c
.RI "u_char * \fBbuff\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file ipheader\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ip_header::ip_header ()"

.PP
Definition at line 12 of file ipheader\&.cpp\&.
.SS "ip_header::ip_header (std::string_dest, std::string_src)"

.PP
Definition at line 35 of file ipheader\&.cpp\&.
.SS "ip_header::~ip_header ()\fC [virtual]\fP"

.PP
Definition at line 29 of file ipheader\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "short unsigned int ip_header::calculateChecksum (\fBip_header\fP *obj, u_char *buff, intn)"

.PP
Definition at line 135 of file ipheader\&.cpp\&.
.SS "unsigned int ip_header::getDestIP ()"

.PP
Definition at line 232 of file ipheader\&.cpp\&.
.SS "unsigned short int ip_header::getLength ()"

.PP
Definition at line 244 of file ipheader\&.cpp\&.
.SS "u_char ip_header::getProtocol ()"

.PP
Definition at line 236 of file ipheader\&.cpp\&.
.SS "unsigned int ip_header::getSrcIP ()"

.PP
Definition at line 228 of file ipheader\&.cpp\&.
.SS "void ip_header::randID (\fBip_header\fP *obj, u_char *&buffer, bool_vlan)"

.PP
Definition at line 159 of file ipheader\&.cpp\&.
.SS "void ip_header::randIP (\fBip_header\fP *obj, u_char *&buffer, bool_vlan, bool_src_ip_flag, bool_dest_ip_flag)"

.PP
Definition at line 192 of file ipheader\&.cpp\&.
.SS "void ip_header::randTTL (\fBip_header\fP *obj, u_char *&buffer, bool_vlan)"

.PP
Definition at line 175 of file ipheader\&.cpp\&.
.SS "void ip_header::serializeIP (\fBip_header\fP *obj, u_char *buff)"

.PP
Definition at line 92 of file ipheader\&.cpp\&.
.SS "void ip_header::setLength (unsigned short int_length)"

.PP
Definition at line 254 of file ipheader\&.cpp\&.
.SS "void ip_header::setProtocol (u_char_protocol)"

.PP
Definition at line 240 of file ipheader\&.cpp\&.
.SS "void ip_header::updateDestIP (\fBip_header\fP *obj, std::string_dest)"

.PP
Definition at line 58 of file ipheader\&.cpp\&.
.SS "void ip_header::updateLength (unsigned short int_length)"

.PP
Definition at line 224 of file ipheader\&.cpp\&.
.SS "void ip_header::updateProtocol (\fBip_header\fP *obj, u_char_protocol)"

.PP
Definition at line 248 of file ipheader\&.cpp\&.
.SS "void ip_header::updateSrcIP (\fBip_header\fP *obj, std::string_src)"

.PP
Definition at line 52 of file ipheader\&.cpp\&.
.SS "void ip_header::updateValues (\fBip_header\fP *obj, u_char_ToS, unsigned short int_length, unsigned short int_id, unsigned short int_flags, unsigned short int_offset, u_char_ttl, u_char_protocol)"

.PP
Definition at line 64 of file ipheader\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "u_char* ip_header::buff = NULL\fC [private]\fP"

.PP
Definition at line 52 of file ipheader\&.h\&.
.SS "short unsigned int ip_header::checksum\fC [private]\fP"

.PP
Definition at line 49 of file ipheader\&.h\&.
.SS "unsigned int ip_header::destip\fC [private]\fP"

.PP
Definition at line 51 of file ipheader\&.h\&.
.SS "unsigned short int ip_header::flags\fC [private]\fP"

.PP
Definition at line 45 of file ipheader\&.h\&.
.SS "unsigned short int ip_header::id\fC [private]\fP"

.PP
Definition at line 44 of file ipheader\&.h\&.
.SS "u_char ip_header::ihl\fC [private]\fP"

.PP
Definition at line 41 of file ipheader\&.h\&.
.SS "unsigned short int ip_header::length\fC [private]\fP"

.PP
Definition at line 43 of file ipheader\&.h\&.
.SS "unsigned short int ip_header::offset\fC [private]\fP"

.PP
Definition at line 46 of file ipheader\&.h\&.
.SS "u_char ip_header::protocol\fC [private]\fP"

.PP
Definition at line 48 of file ipheader\&.h\&.
.SS "unsigned int ip_header::sourceip\fC [private]\fP"

.PP
Definition at line 50 of file ipheader\&.h\&.
.SS "u_char ip_header::ToS\fC [private]\fP"

.PP
Definition at line 42 of file ipheader\&.h\&.
.SS "u_char ip_header::ttl\fC [private]\fP"

.PP
Definition at line 47 of file ipheader\&.h\&.
.SS "u_char ip_header::ver\fC [private]\fP"

.PP
Definition at line 40 of file ipheader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for packet-generator from the source code\&.
