.TH "mainwindow.cpp" 3 "Fri May 13 2016" "Version 1.0" "packet-generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <ifaddrs\&.h>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'workerthread\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for packet-generator from the source code\&.
