.TH "sendSocket" 3 "Fri May 13 2016" "Version 1.0" "packet-generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sendSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sendsocket\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsendSocket\fP ()"
.br
.ti -1c
.RI "\fBsendSocket\fP (std::string _interface, std::string _dest)"
.br
.ti -1c
.RI "\fB~sendSocket\fP ()"
.br
.ti -1c
.RI "void \fBsendPacket\fP (\fBsendSocket\fP *socket, u_char *_send_buff, size_t _size)"
.br
.ti -1c
.RI "void \fBupdateDestMAC\fP (struct sockaddr_ll _struct, std::string _dest)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsocket_fd\fP"
.br
.ti -1c
.RI "struct ifreq \fBinterface_index\fP"
.br
.ti -1c
.RI "struct sockaddr_ll \fBsock_addr\fP"
.br
.ti -1c
.RI "u_char * \fBbuff_layer2\fP = NULL"
.br
.ti -1c
.RI "u_char * \fBbuff_layer3\fP = NULL"
.br
.ti -1c
.RI "u_char * \fBbuff_layer4\fP = NULL"
.br
.ti -1c
.RI "u_char * \fBbuff_begin\fP = NULL"
.br
.ti -1c
.RI "int \fBbuff_size_layer2\fP = 0"
.br
.ti -1c
.RI "int \fBbuff_size_layer3\fP = 0"
.br
.ti -1c
.RI "int \fBbuff_size_layer4\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file sendsocket\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sendSocket::sendSocket ()"
opening socket 
.PP
Definition at line 16 of file sendsocket\&.cpp\&.
.SS "sendSocket::sendSocket (std::string_interface, std::string_dest)"

.PP
Definition at line 42 of file sendsocket\&.cpp\&.
.SS "sendSocket::~sendSocket ()"

.PP
Definition at line 72 of file sendsocket\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void sendSocket::sendPacket (\fBsendSocket\fP *socket, u_char *_send_buff, size_t_size)"

.PP
Definition at line 82 of file sendsocket\&.cpp\&.
.SS "void sendSocket::updateDestMAC (struct sockaddr_ll_struct, std::string_dest)"

.PP
Definition at line 92 of file sendsocket\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "u_char* sendSocket::buff_begin = NULL"

.PP
Definition at line 33 of file sendsocket\&.h\&.
.SS "u_char* sendSocket::buff_layer2 = NULL"

.PP
Definition at line 30 of file sendsocket\&.h\&.
.SS "u_char* sendSocket::buff_layer3 = NULL"

.PP
Definition at line 31 of file sendsocket\&.h\&.
.SS "u_char* sendSocket::buff_layer4 = NULL"

.PP
Definition at line 32 of file sendsocket\&.h\&.
.SS "int sendSocket::buff_size_layer2 = 0"

.PP
Definition at line 34 of file sendsocket\&.h\&.
.SS "int sendSocket::buff_size_layer3 = 0"

.PP
Definition at line 35 of file sendsocket\&.h\&.
.SS "int sendSocket::buff_size_layer4 = 0"

.PP
Definition at line 36 of file sendsocket\&.h\&.
.SS "struct ifreq sendSocket::interface_index"

.PP
Definition at line 25 of file sendsocket\&.h\&.
.SS "struct sockaddr_ll sendSocket::sock_addr"

.PP
Definition at line 26 of file sendsocket\&.h\&.
.SS "int sendSocket::socket_fd"

.PP
Definition at line 24 of file sendsocket\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for packet-generator from the source code\&.
