.TH "tcp_header" 3 "Fri May 13 2016" "Version 1.0" "packet-generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tcp_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcpheader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtcp_header\fP ()"
.br
.ti -1c
.RI "\fBtcp_header\fP (unsigned short int _src_port, unsigned short int _dest_port)"
.br
.ti -1c
.RI "virtual \fB~tcp_header\fP ()"
.br
.ti -1c
.RI "void \fBserializeTCP\fP (\fBtcp_header\fP *obj, u_char *\fBbuff\fP)"
.br
.ti -1c
.RI "void \fBupdateSrcPort\fP (\fBtcp_header\fP *obj, std::string _src)"
.br
.ti -1c
.RI "void \fBupdateDestPort\fP (\fBtcp_header\fP *obj, std::string _dest)"
.br
.ti -1c
.RI "void \fBupdateValues\fP (\fBtcp_header\fP *obj, unsigned short int _src_port, unsigned short int _dest_port, unsigned long int _sequence_number, unsigned long int _acknowledgment_number, u_char _data_offset, u_char _ecn, u_char _control_bits, unsigned short int _window, unsigned short int _urgent_pointer)"
.br
.ti -1c
.RI "short unsigned int \fBcalculateChecksum\fP (\fBtcp_header\fP *obj, \fBip_header\fP *obj2, u_char *\fBbuff\fP, int buff_size)"
.br
.ti -1c
.RI "void \fBupdateChecksum\fP (\fBtcp_header\fP *obj, unsigned short int _checksum)"
.br
.ti -1c
.RI "void \fBupdateOptions\fP (\fBtcp_header\fP *obj, u_char *_options)"
.br
.ti -1c
.RI "void \fBfillData\fP (\fBtcp_header\fP *obj, QString \fBdata\fP)"
.br
.ti -1c
.RI "void \fBrandPort\fP (\fBtcp_header\fP *obj, u_char *&buffer, bool _vlan, bool _src_port, bool _dest_port)"
.br
.ti -1c
.RI "void \fBrandSeqNum\fP (\fBtcp_header\fP *obj, u_char *&buffer, bool _vlan)"
.br
.ti -1c
.RI "void \fBrandAckNum\fP (\fBtcp_header\fP *obj, u_char *&buffer, bool _vlan)"
.br
.ti -1c
.RI "int \fBgetDataSize\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "unsigned short int \fBsrc_port\fP"
.br
.ti -1c
.RI "unsigned short int \fBdest_port\fP"
.br
.ti -1c
.RI "unsigned long int \fBsequence_number\fP"
.br
.ti -1c
.RI "unsigned long int \fBacknowledgment_number\fP"
.br
.ti -1c
.RI "u_char \fBdata_offset\fP"
.br
.ti -1c
.RI "u_char \fBecn\fP"
.br
.ti -1c
.RI "u_char \fBcontrol_bits\fP"
.br
.ti -1c
.RI "unsigned short int \fBwindow\fP"
.br
.ti -1c
.RI "unsigned short int \fBchecksum\fP"
.br
.ti -1c
.RI "unsigned short int \fBurgent_pointer\fP"
.br
.ti -1c
.RI "u_char * \fBoptions\fP = NULL"
.br
.ti -1c
.RI "char * \fBdata\fP = NULL"
.br
.ti -1c
.RI "int \fBdata_size\fP = 0"
.br
.ti -1c
.RI "u_char * \fBbuff\fP = NULL"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file tcpheader\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tcp_header::tcp_header ()"

.PP
Definition at line 10 of file tcpheader\&.cpp\&.
.SS "tcp_header::tcp_header (unsigned short int_src_port, unsigned short int_dest_port)"

.PP
Definition at line 42 of file tcpheader\&.cpp\&.
.SS "tcp_header::~tcp_header ()\fC [virtual]\fP"

.PP
Definition at line 25 of file tcpheader\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "short unsigned int tcp_header::calculateChecksum (\fBtcp_header\fP *obj, \fBip_header\fP *obj2, u_char *buff, intbuff_size)"

.PP
Definition at line 156 of file tcpheader\&.cpp\&.
.SS "void tcp_header::fillData (\fBtcp_header\fP *obj, QStringdata)"

.PP
Definition at line 146 of file tcpheader\&.cpp\&.
.SS "int tcp_header::getDataSize ()"

.PP
Definition at line 285 of file tcpheader\&.cpp\&.
.SS "void tcp_header::randAckNum (\fBtcp_header\fP *obj, u_char *&buffer, bool_vlan)"

.PP
Definition at line 267 of file tcpheader\&.cpp\&.
.SS "void tcp_header::randPort (\fBtcp_header\fP *obj, u_char *&buffer, bool_vlan, bool_src_port, bool_dest_port)"

.PP
Definition at line 220 of file tcpheader\&.cpp\&.
.SS "void tcp_header::randSeqNum (\fBtcp_header\fP *obj, u_char *&buffer, bool_vlan)"

.PP
Definition at line 248 of file tcpheader\&.cpp\&.
.SS "void tcp_header::serializeTCP (\fBtcp_header\fP *obj, u_char *buff)"

.PP
Definition at line 58 of file tcpheader\&.cpp\&.
.SS "void tcp_header::updateChecksum (\fBtcp_header\fP *obj, unsigned short int_checksum)"

.PP
Definition at line 133 of file tcpheader\&.cpp\&.
.SS "void tcp_header::updateDestPort (\fBtcp_header\fP *obj, std::string_dest)"

.PP
Definition at line 109 of file tcpheader\&.cpp\&.
.SS "void tcp_header::updateOptions (\fBtcp_header\fP *obj, u_char *_options)"

.PP
Definition at line 139 of file tcpheader\&.cpp\&.
.SS "void tcp_header::updateSrcPort (\fBtcp_header\fP *obj, std::string_src)"

.PP
Definition at line 103 of file tcpheader\&.cpp\&.
.SS "void tcp_header::updateValues (\fBtcp_header\fP *obj, unsigned short int_src_port, unsigned short int_dest_port, unsigned long int_sequence_number, unsigned long int_acknowledgment_number, u_char_data_offset, u_char_ecn, u_char_control_bits, unsigned short int_window, unsigned short int_urgent_pointer)"

.PP
Definition at line 114 of file tcpheader\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "unsigned long int tcp_header::acknowledgment_number\fC [private]\fP"

.PP
Definition at line 46 of file tcpheader\&.h\&.
.SS "u_char* tcp_header::buff = NULL\fC [private]\fP"

.PP
Definition at line 56 of file tcpheader\&.h\&.
.SS "unsigned short int tcp_header::checksum\fC [private]\fP"

.PP
Definition at line 51 of file tcpheader\&.h\&.
.SS "u_char tcp_header::control_bits\fC [private]\fP"

.PP
Definition at line 49 of file tcpheader\&.h\&.
.SS "char* tcp_header::data = NULL\fC [private]\fP"

.PP
Definition at line 54 of file tcpheader\&.h\&.
.SS "u_char tcp_header::data_offset\fC [private]\fP"

.PP
Definition at line 47 of file tcpheader\&.h\&.
.SS "int tcp_header::data_size = 0\fC [private]\fP"

.PP
Definition at line 55 of file tcpheader\&.h\&.
.SS "unsigned short int tcp_header::dest_port\fC [private]\fP"

.PP
Definition at line 44 of file tcpheader\&.h\&.
.SS "u_char tcp_header::ecn\fC [private]\fP"

.PP
Definition at line 48 of file tcpheader\&.h\&.
.SS "u_char* tcp_header::options = NULL\fC [private]\fP"

.PP
Definition at line 53 of file tcpheader\&.h\&.
.SS "unsigned long int tcp_header::sequence_number\fC [private]\fP"

.PP
Definition at line 45 of file tcpheader\&.h\&.
.SS "unsigned short int tcp_header::src_port\fC [private]\fP"

.PP
Definition at line 43 of file tcpheader\&.h\&.
.SS "unsigned short int tcp_header::urgent_pointer\fC [private]\fP"

.PP
Definition at line 52 of file tcpheader\&.h\&.
.SS "unsigned short int tcp_header::window\fC [private]\fP"

.PP
Definition at line 50 of file tcpheader\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for packet-generator from the source code\&.
