.TH "workerthread.h" 3 "Fri May 13 2016" "Version 1.0" "packet-generator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
workerthread.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QThread>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'includes\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWorkerThread\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for packet-generator from the source code\&.
