ip_header
u_char ip_header::ver
Referenced by ip_header, updateValues, serializeIP.
u_char ip_header::ihl
Referenced by ip_header, updateValues, serializeIP.
u_char ip_header::ToS
Referenced by ip_header, updateValues, serializeIP.
unsigned short int ip_header::length
Referenced by ip_header, updateValues, serializeIP, updateLength, getLength, setLength.
unsigned short int ip_header::id
Referenced by updateValues, serializeIP, randID.
unsigned short int ip_header::flags
Referenced by ip_header, updateValues, serializeIP.
unsigned short int ip_header::offset
Referenced by ip_header, updateValues, serializeIP.
u_char ip_header::ttl
Referenced by ip_header, updateValues, serializeIP, randTTL.
u_char ip_header::protocol
Referenced by ip_header, updateValues, serializeIP, getProtocol, setProtocol, updateProtocol.
short unsigned int ip_header::checksum
Referenced by ip_header, updateValues, serializeIP, calculateChecksum.
unsigned int ip_header::sourceip
Referenced by ip_header, updateSrcIP, serializeIP, randIP, getSrcIP.
unsigned int ip_header::destip
Referenced by ip_header, updateDestIP, serializeIP, randIP, getDestIP.
u_char* ip_header::buff
Referenced by ~ip_header, serializeIP.
ip_header::ip_header()
References ver, ihl, ToS, length, flags, offset, ttl, protocol, sourceip, destip, checksum.
ip_header::ip_header(std::string _dest, std::string _src)
References ver, ihl, ToS, length, flags, offset, ttl, protocol, sourceip, destip, checksum.
ip_header::~ip_header()
References buff.
void ip_header::updateSrcIP(ip_header *obj, std::string _src)
References sourceip.
Referenced by MainWindow::on_SaveL3Button_clicked.
void ip_header::updateDestIP(ip_header *obj, std::string _dest)
References destip.
Referenced by MainWindow::on_SaveL3Button_clicked.
void ip_header::updateValues(ip_header *obj, u_char _ToS, unsigned short int _length, unsigned short int _id, unsigned short int _flags, unsigned short int _offset, u_char _ttl, u_char _protocol)
References ver, ihl, ToS, length, id, flags, offset, ttl, protocol, checksum.
Referenced by MainWindow::on_SaveL3Button_clicked.
void ip_header::serializeIP(ip_header *obj, u_char *buff)
References ver, ihl, buff, ToS, length, id, flags, offset, ttl, protocol, checksum, sourceip, destip.
Referenced by MainWindow::on_SendButton_clicked.
short unsigned int ip_header::calculateChecksum(ip_header *obj, u_char *buff, int n)
References checksum.
Referenced by MainWindow::on_SendButton_clicked, WorkerThread::sendAll.
void ip_header::randID(ip_header *obj, u_char *&buffer, bool _vlan)
References id.
Referenced by MainWindow::randomize.
void ip_header::randTTL(ip_header *obj, u_char *&buffer, bool _vlan)
References ttl.
Referenced by MainWindow::randomize.
void ip_header::randIP(ip_header *obj, u_char *&buffer, bool _vlan, bool _src_ip_flag, bool _dest_ip_flag)
References sourceip, destip.
Referenced by MainWindow::randomize.
void ip_header::updateLength(unsigned short int _length)
References length.
Referenced by MainWindow::on_SendButton_clicked.
unsigned int ip_header::getSrcIP()
References sourceip.
Referenced by tcp_header::calculateChecksum, udp_header::calculateChecksum.
unsigned int ip_header::getDestIP()
References destip.
Referenced by tcp_header::calculateChecksum, udp_header::calculateChecksum.
u_char ip_header::getProtocol()
References protocol.
Referenced by tcp_header::calculateChecksum, udp_header::calculateChecksum.
void ip_header::setProtocol(u_char _protocol)
References protocol.
Referenced by MainWindow::on_checkbox_TCP_create_toggled, MainWindow::on_checkbox_UDP_create_toggled.
unsigned short int ip_header::getLength()
References length.
void ip_header::setLength(unsigned short int _length)
References length.
Referenced by MainWindow::on_SaveL4Button_clicked.
void ip_header::updateProtocol(ip_header *obj, u_char _protocol)
References protocol.
Referenced by MainWindow::on_SendButton_clicked.