WorkerThread
bool WorkerThread::cont
Referenced by sendAll.
WorkerThread::WorkerThread(QObject *parent=0)
void WorkerThread::setCont(bool value)
Referenced by breakSending.
void WorkerThread::finished()
Referenced by sendAll.
void WorkerThread::updateProgress(int _value)
Referenced by sendAll.
void WorkerThread::sendAll(MainWindow *window, sendSocket *socket, ip_header *ip_h, tcp_header *tcp_h, udp_header *udp_h, unsigned short int *to_send_ip, bool ip_cksm, unsigned short int *to_send_tcp, bool tcp_cksm, unsigned short int *to_send_udp, bool udp_cksm)
References updateProgress, finished, MainWindow::getNumOfPackets, cont, MainWindow::randomize, MainWindow::getRandFlags, tcp_header::calculateChecksum, sendSocket::buff_begin, sendSocket::buff_size_layer2, sendSocket::buff_size_layer3, sendSocket::buff_size_layer4, udp_header::calculateChecksum, ip_header::calculateChecksum, sendSocket::sendPacket.
void WorkerThread::breakSending()
References setCont.