udp_header
unsigned short int udp_header::src_port
Referenced by udp_header, serializeUDP, updateSrcPort, updateValues, randPort.
unsigned short int udp_header::dest_port
Referenced by udp_header, serializeUDP, updateDestPort, updateValues, randPort.
unsigned short int udp_header::length
Referenced by udp_header, serializeUDP, updateValues.
unsigned short int udp_header::checksum
Referenced by udp_header, updateValues, calculateChecksum, updateChecksum.
char* udp_header::data
Referenced by ~udp_header, serializeUDP, fillData.
int udp_header::data_size
Referenced by serializeUDP, fillData.
u_char* udp_header::buff
Referenced by ~udp_header, serializeUDP.
udp_header::udp_header()
References src_port, dest_port, length, checksum.
udp_header::udp_header(unsigned short int _src_port, unsigned short int _dest_port)
References src_port, dest_port, length, checksum.
udp_header::~udp_header()
References data, buff.
void udp_header::serializeUDP(udp_header *obj, u_char *buff)
References src_port, dest_port, length, data_size, data, buff.
Referenced by MainWindow::on_SendButton_clicked.
void udp_header::updateSrcPort(udp_header *obj, std::string _src_port)
References src_port.
void udp_header::updateDestPort(udp_header *obj, std::string _dest_port)
References dest_port.
void udp_header::updateValues(udp_header *obj, unsigned short int _src_port, unsigned short int _dest_port, unsigned short int _length)
References src_port, dest_port, length, checksum.
Referenced by MainWindow::on_SaveL4Button_clicked.
unsigned short int udp_header::calculateChecksum(udp_header *obj, ip_header *obj2, u_char *buff, int buff_size)
References ip_header::getSrcIP, ip_header::getDestIP, ip_header::getProtocol, checksum.
Referenced by WorkerThread::sendAll.
void udp_header::updateChecksum(udp_header *obj, unsigned short int _checksum)
References checksum.
void udp_header::fillData(udp_header *obj, QString _data)
References data, data_size.
Referenced by MainWindow::on_SaveL4Button_clicked.
void udp_header::randPort(udp_header *obj, u_char *&buffer, bool _vlan, bool _src_port, bool _dest_port)
References src_port, dest_port.
Referenced by MainWindow::randomize.