eth_802Q
u_char eth_802Q::DestMac[6][6]
Referenced by eth_802Q, updateDestMAC, serializeEth802Q.
u_char eth_802Q::SrcMac[6][6]
Referenced by eth_802Q, updateSrcMAC, serializeEth802Q.
u_char eth_802Q::TPID[2][2]
Referenced by eth_802Q, serializeEth802Q.
u_char eth_802Q::TCI[2][2]
Referenced by eth_802Q, updateTCI, serializeEth802Q.
u_char eth_802Q::Type[2][2]
Referenced by eth_802Q, serializeEth802Q.
u_char* eth_802Q::buff
Referenced by ~eth_802Q, serializeEth802Q.
eth_802Q::eth_802Q()
References SrcMac, DestMac, TPID, TCI, Type.
eth_802Q::eth_802Q(std::string _dest, std::string _src, int _pcp, int _dei, int _vid)
References SrcMac, DestMac, TPID, TCI, Type.
eth_802Q::~eth_802Q()
References buff.
void eth_802Q::updateSrcMAC(eth_802Q *obj, std::string _src)
References SrcMac.
Referenced by MainWindow::on_SaveL2Button_clicked.
void eth_802Q::updateDestMAC(eth_802Q *obj, std::string _dest)
References DestMac.
Referenced by MainWindow::on_SaveL2Button_clicked.
void eth_802Q::updateTCI(eth_802Q *obj, int _tci)
References TCI.
Referenced by MainWindow::on_SaveL2Button_clicked.
void eth_802Q::serializeEth802Q(eth_802Q *obj, u_char *_buff)
References SrcMac, DestMac, TPID, buff, TCI, Type.
Referenced by MainWindow::on_SendButton_clicked.
void eth_802Q::randPCP(u_char *&buffer)
Referenced by MainWindow::randomize.
void eth_802Q::randomMACAddr(u_char *&buffer, bool _rand_dest_flag, bool _rand_src_flag)
Referenced by MainWindow::randomize.
void eth_802Q::randDEI(u_char *&buffer)
Referenced by MainWindow::randomize.
void eth_802Q::randVID(u_char *&buffer)
Referenced by MainWindow::randomize.