tcp_header
unsigned short int tcp_header::src_port
unsigned short int tcp_header::dest_port
unsigned long int tcp_header::sequence_number
unsigned long int tcp_header::acknowledgment_number
u_char tcp_header::data_offset
u_char tcp_header::ecn
u_char tcp_header::control_bits
unsigned short int tcp_header::window
unsigned short int tcp_header::checksum
unsigned short int tcp_header::urgent_pointer
u_char* tcp_header::options
char* tcp_header::data
int tcp_header::data_size
u_char* tcp_header::buff
tcp_header::tcp_header()
tcp_header::tcp_header(unsigned short int _src_port, unsigned short int _dest_port)
tcp_header::~tcp_header()
void tcp_header::serializeTCP(tcp_header *obj, u_char *buff)
void tcp_header::updateSrcPort(tcp_header *obj, std::string _src)
void tcp_header::updateDestPort(tcp_header *obj, std::string _dest)
void tcp_header::updateValues(tcp_header *obj, unsigned short int _src_port, unsigned short int _dest_port, unsigned long int _sequence_number, unsigned long int _acknowledgment_number, u_char _data_offset, u_char _ecn, u_char _control_bits, unsigned short int _window, unsigned short int _urgent_pointer)
short unsigned int tcp_header::calculateChecksum(tcp_header *obj, ip_header *obj2, u_char *buff, int buff_size)
References ip_header::getSrcIP, ip_header::getDestIP, ip_header::getProtocol.
Referenced by WorkerThread::sendAll.
void tcp_header::updateChecksum(tcp_header *obj, unsigned short int _checksum)
void tcp_header::updateOptions(tcp_header *obj, u_char *_options)
void tcp_header::fillData(tcp_header *obj, QString data)
void tcp_header::randPort(tcp_header *obj, u_char *&buffer, bool _vlan, bool _src_port, bool _dest_port)
Referenced by MainWindow::randomize.
void tcp_header::randSeqNum(tcp_header *obj, u_char *&buffer, bool _vlan)
Referenced by MainWindow::randomize.
void tcp_header::randAckNum(tcp_header *obj, u_char *&buffer, bool _vlan)
Referenced by MainWindow::randomize.
int tcp_header::getDataSize()