MainWindow
QThread* MainWindow::thread
Referenced by MainWindow, ~MainWindow, on_SendButton_clicked.
Ui::MainWindow* MainWindow::ui
Referenced by MainWindow, ~MainWindow, on_SaveL2Button_clicked, on_SaveL3Button_clicked, on_SaveL4Button_clicked, on_SendButton_clicked, setFlags, randomize, on_checkBox_ip_create_toggled, on_checkBox_eth_vlan_toggled, on_checkbox_TCP_create_toggled, on_checkbox_UDP_create_toggled, fillEthTable, fillIPTable, updateTableIPLength, fillTCPTable, fillUDPTable, setValidators, updateProgress, checkMTU.
eth_header* MainWindow::eth_h
Referenced by ~MainWindow, on_SaveL2Button_clicked, on_SaveL3Button_clicked, on_SaveL4Button_clicked, on_SendButton_clicked, randomize, updateTableIPLength.
eth_802Q* MainWindow::vlan_h
Referenced by ~MainWindow, on_SaveL2Button_clicked, on_SaveL3Button_clicked, on_SaveL4Button_clicked, on_SendButton_clicked, randomize, fillEthTable, fillIPTable, updateTableIPLength, checkMTU.
ip_header* MainWindow::ip_h
Referenced by ~MainWindow, on_SaveL3Button_clicked, on_SaveL4Button_clicked, on_SendButton_clicked, randomize, on_checkBox_ip_create_toggled, on_checkbox_TCP_create_toggled, on_checkbox_UDP_create_toggled.
tcp_header* MainWindow::tcp_h
Referenced by ~MainWindow, on_SaveL4Button_clicked, on_SendButton_clicked, randomize, on_checkbox_TCP_create_toggled, on_checkbox_UDP_create_toggled, checkMTU.
udp_header* MainWindow::udp_h
Referenced by ~MainWindow, on_SaveL4Button_clicked, on_SendButton_clicked, randomize, on_checkbox_UDP_create_toggled, checkMTU.
sendSocket* MainWindow::socket
Referenced by ~MainWindow, on_SendButton_clicked, sendingFinished, randomize.
unsigned MainWindow::threads
Referenced by MainWindow, on_packages_to_send_lineEdit_textEdited.
double MainWindow::num_of_packets
Referenced by on_SendButton_clicked, getNumOfPackets.
bool* MainWindow::flags
Referenced by ~MainWindow, on_SaveL3Button_clicked, setFlags, fillIPTable.
bool* MainWindow::rand_flags
Referenced by ~MainWindow, on_SendButton_clicked, getRandFlags.
QElapsedTimer MainWindow::timer
Referenced by on_SendButton_clicked, updateProgress.
struct ifaddrs* MainWindow::addrs
Referenced by MainWindow, ~MainWindow.
struct ifaddrs* MainWindow::ipa
Referenced by MainWindow.
QIntValidator* MainWindow::valid0to7
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0and1
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to4095
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to63
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to2
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to65535
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to8191
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to255
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::valid0to15
Referenced by ~MainWindow, setValidators.
QDoubleValidator* MainWindow::valid_double
Referenced by ~MainWindow, setValidators.
QIntValidator* MainWindow::validMTU
Referenced by ~MainWindow, setValidators.
QColor MainWindow::orange
Referenced by fillTCPTable, fillUDPTable.
QColor MainWindow::green
Referenced by fillTCPTable.
QColor MainWindow::blue
Referenced by fillUDPTable.
QColor MainWindow::red
QColor MainWindow::gray
Referenced by fillTCPTable, fillUDPTable.
MainWindow::MainWindow(QWidget *parent=0)
References ui, setValidators, addrs, ipa, threads, thread, start, stop, sendingFinished.
MainWindow::~MainWindow()
References thread, valid0to7, valid0and1, valid0to4095, valid0to63, valid0to2, valid0to65535, valid0to8191, valid0to255, valid0to15, valid_double, validMTU, addrs, socket, rand_flags, flags, eth_h, vlan_h, ip_h, tcp_h, udp_h, ui.
double MainWindow::getNumOfPackets()
References num_of_packets.
Referenced by WorkerThread::sendAll.
void MainWindow::updateProgress(int _value)
References ui, timer.
void MainWindow::sendingFinished()
References socket, sendSocket::buff_layer2, sendSocket::buff_layer3, sendSocket::buff_layer4, sendSocket::buff_begin.
Referenced by MainWindow.
void MainWindow::randomize(bool *flags)
References ui, vlan_h, eth_802Q::randomMACAddr, socket, sendSocket::buff_begin, eth_h, eth_header::randomMACAddr, eth_802Q::randPCP, eth_802Q::randDEI, eth_802Q::randVID, ip_h, ip_header::randID, ip_header::randTTL, ip_header::randIP, tcp_h, tcp_header::randPort, tcp_header::randSeqNum, tcp_header::randAckNum, udp_h, udp_header::randPort.
Referenced by WorkerThread::sendAll.
bool * MainWindow::getRandFlags()
References rand_flags.
Referenced by WorkerThread::sendAll.
void MainWindow::on_SaveL2Button_clicked()
References ui, eth_h, vlan_h, eth_802Q::updateSrcMAC, eth_802Q::updateDestMAC, eth_802Q::updateTCI, eth_header::updateSrcMAC, eth_header::updateDestMAC, fillEthTable.
void MainWindow::on_SaveL3Button_clicked()
References eth_h, vlan_h, ip_h, ui, flags, ip_header::updateSrcIP, ip_header::updateDestIP, ip_header::updateValues, fillEthTable, fillIPTable.
void MainWindow::on_SaveL4Button_clicked()
References cleanTable, ui, eth_h, vlan_h, fillEthTable, ip_h, fillIPTable, udp_h, tcp_h, checkMTU, tcp_header::fillData, tcp_header::updateValues, updateTableIPLength, fillTCPTable, udp_header::fillData, udp_header::updateValues, fillUDPTable, ip_header::setLength.
void MainWindow::on_checkBox_eth_vlan_toggled(bool checked)
References ui.
void MainWindow::on_SendButton_clicked()
References ui, socket, sendSocket::interface_index, num_of_packets, timer, tcp_h, udp_h, sendSocket::buff_size_layer4, sendSocket::buff_layer4, tcp_header::serializeTCP, sendSocket::buff_layer3, sendSocket::buff_size_layer3, ip_h, ip_header::updateLength, ip_header::serializeIP, ip_header::calculateChecksum, ip_header::updateProtocol, sendSocket::buff_layer2, sendSocket::buff_size_layer2, vlan_h, eth_802Q::serializeEth802Q, eth_h, eth_header::serializeEth, udp_header::serializeUDP, fillEthTable, sendSocket::buff_begin, rand_flags, setFlags, thread, start.
void MainWindow::on_checkBox_ip_create_toggled(bool checked)
References ui, cleanTable, ip_h.
void MainWindow::on_checkbox_TCP_create_toggled(bool checked)
References ui, ip_h, ip_header::setProtocol, cleanTable, updateTableIPLength, tcp_h.
void MainWindow::on_checkbox_UDP_create_toggled(bool checked)
References tcp_h, ui, ip_h, ip_header::setProtocol, cleanTable, updateTableIPLength, udp_h.
void MainWindow::on_packages_to_send_lineEdit_textEdited(const QString &arg1)
References threads.
void MainWindow::fillEthTable()
References ui, vlan_h.
Referenced by on_SaveL2Button_clicked, on_SaveL3Button_clicked, on_SaveL4Button_clicked, on_SendButton_clicked.
void MainWindow::fillIPTable()
References vlan_h, ui, flags.
Referenced by on_SaveL3Button_clicked, on_SaveL4Button_clicked.
void MainWindow::fillTCPTable()
References ui, green, gray, orange.
Referenced by on_SaveL4Button_clicked.
void MainWindow::fillUDPTable()
References ui, blue, orange, gray.
Referenced by on_SaveL4Button_clicked.
void MainWindow::updateTableIPLength(int l4_length, int data_length)
References vlan_h, eth_h, ui.
Referenced by on_SaveL4Button_clicked, on_checkbox_TCP_create_toggled, on_checkbox_UDP_create_toggled.
void MainWindow::setValidators()
References ui, valid0to7, valid0and1, valid0to4095, valid0to63, valid0to2, valid0to65535, valid0to8191, valid0to255, valid0to15, valid_double, validMTU.
Referenced by MainWindow.
void MainWindow::cleanTable(QTableWidget *table)
Referenced by on_SaveL4Button_clicked, on_checkBox_ip_create_toggled, on_checkbox_TCP_create_toggled, on_checkbox_UDP_create_toggled.
bool * MainWindow::setFlags()
References flags, ui.
Referenced by on_SendButton_clicked.
void MainWindow::on_stop_pushButton_clicked()
References stop.
bool MainWindow::checkMTU()
References ui, udp_h, vlan_h, tcp_h.
Referenced by on_SaveL4Button_clicked.
void MainWindow::start(MainWindow *, sendSocket *, ip_header *, tcp_header *, udp_header *, unsigned short int *, bool, unsigned short int *, bool, unsigned short int *, bool)
Referenced by MainWindow, on_SendButton_clicked.
void MainWindow::stop()
Referenced by MainWindow, on_stop_pushButton_clicked.